### ISSUE TITLE
Adding extra message

### ISSUE THREAD

**Issue by mfc-julius** [vanjacosic/opbeat-js#5]
First of all, great software! We managed to integrate it with our Angular app + StackTrace.

However, logging a standard exception has a limited length on Opbeat. Though Opbeat provides a possibility to add an extra message. Would you consider integrated this to opbeat-js?

On our side it's opbeat-js + stacktrace-js + custom Angular services, that are logging errors with the printStackTrace method.

**Comment by vanjacosic** [comment]
Hi @mfc-julius, thanks for the praise! I'm glad it's working for you despite being totally pre-alpha software :grin: 

With regards to message length:
When looking at an error group in Opbeat, the message at the top of the view is truncated but the message in the Exception tab (called `Value`) allows for much more content.

So what I've done in the PR referenced above, is to up that limit from 100 to 500 in the library. That should allow you to see a much longer message in the Exception tab for the error group.

The reason this is not unlimited is because we could potentially run into issues with the limit of how long URLs browsers can handle. The way we send the data from Opbeat-JS to Opbeat.com is by encoding all the data in a URL and doing a get request on it. If that gets too long some browsers might not handle it very well. 

Some discussion about those topics:

http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers/417184#417184 - This says a limit of around 2000 to be safe, which we can easily go past currently, but still seems to work.

http://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string - This says that the limit is way higher, and if that's the case we should be good with removing truncation. 

But the dilemma is, that I don't know - so further testing is needed. 

But for now, @mfc-julius - can you try out the version of the library in the PR and see if it helps you for now? And see if it gives you any issues in different browsers.

Let me know!

**Comment by mfc-julius** [comment]
I see the Exception tab on our Django apps, but there's no tab for JS app. Also, even on Django app the message is truncated (see image below) - unless that's where it has been limited to 500 now?

![Exception](http://s21.postimg.org/c2n6r749z/Screen_Shot_2015_07_30_at_17_27_06.png)

Well, was there a reason for encoding a message in a URL and sending a GET request? Can't it be POST sending JSON?

**Comment by vanjacosic** [comment]
The Exception tab shows up if the payload that is sent contains a `exception` object containing a `type` and `value`. I'm guessing that is because you're using stacktrace.js it's not getting picked up by Opbeat-JS as an exception but rather just a message. See sourcecode for difference between `captureMessage()` and `captureException()` - maybe you can find the problem there?

There's no truncation on our end for the `Value` field in the Exception data. We have some apps where the message in `Value` is thousands of chars long. So truncation in the screenshot above is not happening on our end AFAIK :)

The reason was simply, that that was the way it was done in the original library we forked. That method of sending the data by encoding it into the URL of an image file is just very robust as it will work an all browser (there is of course the URL length challenge). But I have considered replacing it with a lightweight xhr wrapper that could make proper requests with a JSON payload. I just don't have the bandwidth for that at the moment. Such a solution would need to be tested thoroughly on a lot of different browsers.

Hope that helps!

**Comment by mfc-julius** [comment]
Right, so I'm not using stacktrace.js anymore, and everything seems to be better now. Only adding an extra message with full URL (from the window, not the file where an error occurred), with options (that's what I needed, it's not obvious whilst not documented).

Obviously, now the problem is that minified JS file is used, and pretty much it's impossible to track down where the error actually is. I saw there's a PR for adding the info of columns to Extra, I'll try that then. So 100 to 500 increase may not be needed?
